# WIP (B29, Jan-23) {#b29}

```{r 'B29', include=FALSE, cache=FALSE}
sys.source(paste0(.z$RX, "A99Knitr", ".R"), envir = knitr::knit_global())
sys.source(paste0(.z$RX, "000Packages", ".R"), envir = knitr::knit_global())
sys.source(paste0(.z$RX, "A00AllUDF", ".R"), envir = knitr::knit_global())
#invisible(lapply(f_getPathR(A09isPrime), knitr::read_chunk))
```


## Overview

- "Ridge, Lasso and Elastic Net regressions"

```{r 'B29-namesXL', include=FALSE, eval=FALSE}
# #Object Names for each sheet
namesXL <- c("xxB26Hdesc", "xxB26Hraw", "xxB26Hmod")
```

```{r 'B29-ImportData', include=FALSE, eval=FALSE}
for(ii in seq_along(namesXL)){
  assign(namesXL[ii], readRDS(paste0(.z$XL, namesXL[ii], ".rds")))
}
```

```{r 'B29-getKC', include=FALSE, eval=FALSE}
# #Load Data: KC House
xxB26KC <- f_getRDS(xxB26KC)
bb <- aa <- xxB26KC
```


## WIP


```{r 'B29-1', include=FALSE, eval=FALSE}
data("BostonHousing")
bb <- BostonHousing
#
```


```{r 'B29-2', include=FALSE, eval=FALSE}
pairs.panels(bb[c(-4,-14)], cex = 2)
```


```{r 'B29-3', include=FALSE, eval=FALSE}
set.seed (1234)
index <- sample(2, nrow(bb), replace = TRUE, prob = c(.70,.30))
train <- bb[index ==1, ]
test <- bb[index ==2, ]
```


```{r 'B29-4', include=FALSE, eval=FALSE}
#custom control parameters

custom <- trainControl(method = "repeatedcv", number = 10, repeats = 5)
```


```{r 'B29-5', include=FALSE, eval=FALSE}
# RUNNING A LINEAR REGRESSION MODEL
set.seed (1234)
linear <- train(medv~., train, method = "lm", trControl = custom)
linear$results
#linear
#summary(linear)
linear1 <- lm(medv~., data = train)# no cross validation 
#summary(linear1)
```


```{r 'B29-6', include=FALSE, eval=FALSE}
# RIDGE REGRESSION
set.seed (1234)

ridge <- train (medv~., train, method = "glmnet", 
                tuneGrid = expand.grid(alpha = 0, lambda = seq(0.0001, 1, length = 5)), 
                trControl = custom)
#ridge
#plot(ridge)
#plot (ridge$finalModel, xvar = "lambda", label = TRUE)
#plot(varImp(ridge, scale = TRUE))# draw variable importance plot
```


```{r 'B29-7', include=FALSE, eval=FALSE}
#LASSO REGRESSION(LASSO" stands for Least Absolute Shrinkage and Selection Operator)
set.seed(1234)

lasso <- train (medv~., train, method = "glmnet",
                tuneGrid = expand.grid(alpha = 1, lambda = seq(0.0001, 1, length = 5)), 
                trControl = custom)
#lasso
#plot(lasso)
#plot(varImp(lasso, scale = TRUE))
```


```{r 'B29-8', include=FALSE, eval=FALSE}
#ELASTIC NET REGRESSION
set.seed (1234)

elastic <- train (medv~., train, method = "glmnet", 
                  tuneGrid = expand.grid(alpha = seq(0,1, length = 10), 
                                         lambda = seq(0.0001, 1, length = 5)), trControl = custom)
#plot(elastic)
#elastic <- train (medv~., train, method = "glmnet", 
#                  tuneGrid = expand.grid(alpha = seq(0,1, length = 10), 
#                                         lambda = seq(0.0001, 0.2, length = 5)),
#                  trControl = custom)

#elastic
#varImp(elastic)
#plot(varImp(elastic))
```


```{r 'B29-9', include=FALSE, eval=FALSE}
## COMPARE THE MODEL
modellist <- list (linear = linear, lasso = lasso, ridge = ridge, elastic = elastic)
compare <- resamples(modellist)
#summary(compare)
```


```{r 'B29-10', include=FALSE, eval=FALSE}
## BEST MODEL
ridge$bestTune
lasso$bestTune
elastic$bestTune
```


```{r 'B29-11', include=FALSE, eval=FALSE}
## to examine the coefficients
best <-elastic$finalModel
coef(best, s = elastic$bestTune$lambda)
```


```{r 'B29-12', include=FALSE, eval=FALSE}
#saveRDS(elastic, "finalmodel.rds")
#final <-readRDS("finalmodel.rds")
#print(final)
final <- elastic
```


```{r 'B29-13', include=FALSE, eval=FALSE}
##### PREDICTION
P1<- predict(final, train)
sqrt(mean((train$medv-P1)^2))


P2<- predict(final, test)
sqrt(mean((test$medv-P2)^2))

P2<- predict(linear, test)
sqrt(mean((test$medv-P2)^2))
```



## Validation {.unlisted .unnumbered .tabset .tabset-fade}

```{r 'B29-Cleanup', include=FALSE, cache=FALSE}
f_rmExist(aa, bb, ii, jj, kk, ll, ff, xxB26Hdesc, xxB26Hmod, xxB26Hraw, xxB26KC, namesXL)
```

```{r 'B29-Validation', include=FALSE, cache=FALSE}
# #SUMMARISED Packages and Objects (BOOK CHECK)
f_()
#
difftime(Sys.time(), k_start)
```

****
