# WIP (B34, Feb-27) {#b34 .unlisted .unnumbered}

```{r 'B34', include=FALSE, cache=FALSE, eval=FALSE}
sys.source(paste0(.z$RX, "A99Knitr", ".R"), envir = knitr::knit_global())
sys.source(paste0(.z$RX, "000Packages", ".R"), envir = knitr::knit_global())
sys.source(paste0(.z$RX, "A00AllUDF", ".R"), envir = knitr::knit_global())
#invisible(lapply(f_getPathR(A09isPrime), knitr::read_chunk))
```

> "Incomplete"

## Overview

- Classification

## Logistic Regression

## Data: Bank {#set-bank-b34 .tabset .tabset-fade}

\textcolor{pink}{Please import the "B34-bank-full.csv"}

```{r 'B34-Bank', include=FALSE, eval=FALSE}
# #Path of Object, FileName and MD5Sum tools::md5sum(paste0(.z$XL, "B34-bank-full.csv"))
#xxB34Bank <- f_getObject("xxB34Bank", "B34-bank-full.csv",
                                #"e6b0ca77f3f200ec5428e04dd104da53")
loc_src <- paste0(.z$XL, "B34-bank-full", ".csv")
loc_rds <- paste0(.z$XL, "xxB34Bank", ".rds")
tbl <- read_delim(file = paste0(.z$XL, "B34-bank-full.csv"), delim = ";")
attr(tbl, "spec") <- NULL
attr(tbl, "problems") <- NULL
saveRDS(tbl, loc_rds)
```

```{r 'B34-GetBank', include=FALSE, eval=FALSE}
xxB34Bank <- f_getRDS(xxB34Bank)
```

### EDA {.unlisted .unnumbered}


```{r 'B34-T1', eval=FALSE}
aa <- xxB34Bank
#
bb <- aa %>% 
  #mutate(across(where(is.character) & !c(y), factor)) %>% 
  mutate(across(where(is.character), factor)) %>% 
  relocate(y) %>% 
  select(-c(job, month))
#
xfw <- bb
```


```{r 'B34-T2', eval=FALSE}
# #Partition Data
set.seed(3)
# #Create Dummies | Replaced All NA in original data so no replacement in dummy columns |
#dum_xfw <- dummy_cols(xfw, 
#  select_columns = c("marital", "education", "default", "housing", "loan", "contact", "poutcome"), 
#                      remove_first_dummy = TRUE, remove_selected_columns = TRUE) 
dum_xfw <- dummy_cols(xfw, 
  select_columns = c("marital", "education", "default", "housing", "loan", "contact", "poutcome"),
                      remove_first_dummy = TRUE, remove_selected_columns = TRUE) 
idx_xsyw <- sample.int(n = nrow(dum_xfw), size = floor(0.8 * nrow(dum_xfw)), replace = FALSE)
train_xfw <- dum_xfw[idx_xsyw, ] 
test_xfw  <- dum_xfw[-idx_xsyw, ]
```


### Structure {.unlisted .unnumbered}


```{r 'B34-Temp-Bank', include=TRUE, eval=FALSE}
# #Count NA 
if(FALSE) colSums(is.na(aa)) %>% as_tibble(rownames = "Cols") %>% filter(value > 0)
#
if(FALSE) bb %>% select(isFemale) %>% slice(1:10)
if(FALSE) cat('"', paste0(levels(bb$Arrival), collapse = '", "'), '"\n', sep = '')
if(FALSE) bb %>% filter(is.na(bpl)) %>% select(id, bph, bpl)
if(FALSE) bb %>% select(isImplant, imp_c) %>% summary()
if(FALSE) bb %>% select(iFemale, iMarried, iEmergency, iImplant) %>% 
  pivot_longer(everything()) %>% 
  count(name, value) %>% 
  pivot_wider(names_from = value, values_from = n) 
# #Count Unique of all Columns to decide which should be Factors
if(FALSE) bb %>% summarise(across(everything(), ~ length(unique(.)))) %>% pivot_longer(everything())
# #Summary of Columns of a class: is.factor is.numeric is.character
if(FALSE) bb %>% select(!where(is.factor)) %>% summary()
# #Names and Indices of Columns of class: is.factor is.numeric is.character
if(FALSE) which(sapply(bb, is.factor))
# #Comma separated string having each item within quotes for easy pasting as character not objects
if(TRUE) cat('"', paste0(names(which(sapply(bb, is.factor))), collapse = '", "'), '"\n', sep = '')
# #Levels of Factor Columns
if(FALSE) lapply(bb[c(3, 6:9, 15)], levels)
# #Frequency of Each level of Factor
if(FALSE) bb %>% count(y) %>% arrange(desc(n))
```

```{r 'B34-Structure-Bank', eval=FALSE}
str(bb)
```

### Summary {.unlisted .unnumbered}

```{r 'B34-Summary-Bank', eval=FALSE}
summary(bb)
```


## PERFORM LOGISTIC REGRESSION


```{r 'B34-T3', eval=FALSE}
mod_xfw_glm <- glm(y ~ ., family = binomial, data = train_xfw)
```

```{r 'B34-Print-Default-1', echo=FALSE, collapse=FALSE, class.output="models", eval=FALSE}
# #Coefficient Estimates, RSE, R2, F-statistic, Significance, DF
ttl_hh <- "Logistic Regression: Bank: Y ~ X"
col_hh <- c("ALL")
#
stargazer(mod_xfw_glm, 
    title = ttl_hh, column.labels = col_hh, model.numbers = FALSE, df = FALSE, report = "vc*", 
    type = "text", single.row = TRUE, intercept.bottom = FALSE, dep.var.caption = "", digits = 4)
```



```{r 'B34-T4', eval=FALSE}
#summary(mod_xfw_glm)
stargazer(mod_xfw_glm, type = "text", single.row = TRUE, intercept.bottom = FALSE)
```

## Validation {.unlisted .unnumbered .tabset .tabset-fade}

```{r 'B34-Cleanup', include=FALSE, cache=FALSE, eval=FALSE}
f_rmExist(aa, bb, ii, jj, kk, ll)
```

```{r 'B34-Validation', include=FALSE, cache=FALSE, eval=FALSE}
# #SUMMARISED Packages and Objects (BOOK CHECK)
f_()
#
difftime(Sys.time(), k_start)
```

****
